### ISSUE TITLE
Bulk insert to existing table with different schema

### ISSUE THREAD

**Issue by chillifoot** [zzzprojects/Bulk-Operations#12]
Hello,

We have a table already defined in our DB that we are using your library to bulk insert to. The incoming data has changed in column definition and we now have more columns than the existing table. I was expecting the bulk insert to fail, however, it works without issue and just ignores the new columns in the data we are trying to insert.

Is there anyway to check that the receiving table is the same definition as the source data? How do you handle these scenarios?

Thanks

c

**Comment by JonathanMagnan** [comment]
Hello @chillifoot ,

I will assume in my question you are using the AutoMapping and not explicitly provide the mapping to our library.

The AutoMapping will try to map every database column with the source. If something is found with the same name, it will be mapped other that will be skipped. 

That's why when you add an additional column in the database, nothing will fail since they will simply not be mapped or automatically mapped if something in the source already existed with the same name.

If you want, we can add a new option that will raise an error if not all database columns are mapped. However, I'm not sure if I would recommend such option.

Let me know if my answer is clear and if there is something we could do to help you like adding this option.

Best Regards,

Jonathan

**Comment by chillifoot** [comment]
Hello Jonathan,

Thanks again for your quick reply!

An option to raise an error if the incoming data was different to the target destination would be great for our usecase. Our destination tables are static so if the incoming data schema has changed we would like to flag this up. A schema compare between source object and destination table would an ideal option.

Thanks

c

**Comment by JonathanMagnan** [comment]
Great,

We will try to add this option over this weekend or early next week.

I will let you know as soon as this new version is ready.

Best Regards,

Jonathan

**Comment by chillifoot** [comment]
Excellent! Thanks Jonathan.

**Comment by JonathanMagnan** [comment]
Hello @chillifoot ,

The v2.12.1 has been released:
https://www.nuget.org/packages/Z.BulkOperations/

We added 2 new options:
- ValidateAllSourceMapped option. When enabled, all members from the source must be mapped otherwise an error is thrown.
- ValidateAllDestinationMapped option. When enabled, all columns from the destination must be mapped otherwise an error is thrown. 

Release Note: https://github.com/zzzprojects/Bulk-Operations/releases/tag/v2.12.1

Let me know if theses options solve your requirement.

Best Regards,

Jonathan

**Comment by chillifoot** [comment]
Hello Jonathan,

Apologies for the delay in coming back to you and thanks for the new version. I will have a look and get back to you with any questions or comments!

Thanks

**Comment by chillifoot** [comment]
Hello Jonathan,

Works great. Many thanks for the additions!

Thanks

**Comment by JonathanMagnan** [comment]
Closing Comment: Fixed
