### ISSUE TITLE
How to validate all providers?

### ISSUE THREAD

**Issue by AndreaA86** [zzzprojects/Bulk-Operations#26]
Hi,
I purchase the All Providers option for BUlkOperations.
I see that if I use the ValidateLincense method() (Z.BulkOperations.LicenseManager class) I can validate a specific provider (e.g. SQLServer).
If I want to validate all providers in a single time I can use the "ProviderType.None" enum value as parameter? Or I must call the ValidateLincense(ProviderType) for each provider?

Thanks
Andrea

**Comment by JonathanMagnan** [comment]
Hello @AndreaA86 ,

Unfortunately, there is no "All Providers" validation. You will need to check one by one all providers you use.

However, you only have to validate one really. Since by looking at one provider, you ensure the license has been added correctly which is the most important part. Your license always enables all providers.

Let me know if that answer correctly to your question.

Best Regards,

Jonathan

**Comment by AndreaA86** [comment]
Ah ok.
Therefore if I call only ValidateLicense() (SQLServer default), the license enable all included providers.

**Comment by JonathanMagnan** [comment]
Exactly ;)

**Comment by AndreaA86** [comment]
Perfect.
Thanks.
