### ISSUE TITLE
BulkInsert errors when using InsertIfNotExists and ColumnMappings.

### ISSUE THREAD

**Issue by codyspeck** [zzzprojects/Bulk-Operations#49]
Given the following table in SQL Server:

```sql
CREATE TABLE Product (
    Name nvarchar(50) null
);
```

The following code throws an error:

```c#
class Product
{
    public string Name { get; set; }
}

static void InsertBroken()
{
    using (var connection = new SqlConnection(ConnectionString))
    using (var bulk = new BulkOperation(connection))
    {
        connection.Open();

        var products = new List<Product>
        {
            new Product { Name = "Name" }
        };

        bulk.ColumnMappings = new List<ColumnMapping>
        {
            new ColumnMapping("Name", "Name")
        };
        bulk.DestinationTableName = "Product";
        bulk.AutoMapKeyName = "Name";
        bulk.InsertIfNotExists = true;

        bulk.BulkInsert(products);
    }
}
```
"System.Exception: 'An error occured, no primary key could be found or resolved.'"

If the `ColumnMapping`s aren't set, then this code works fine. The `ColumnMapping` is not needed for this example, but they are for my actual use case.

Is there anything I can do to get around this or is this a bug?

**Comment by JonathanMagnan** [comment]
Hello @codyspeck ,

It works as expected.

Anything with the prefix `AutoMap` only are taken if there is no mapping. In other words, the auto mapping only happens if there is no mapping.

 If you specify the mapping, you should be able to specify that the column is also a key

```
bulk.ColumnMappings = new List<ColumnMapping>
        {
            new ColumnMapping("Name", "Name", true)
        };
```

Let me know if that explains correctly why this behavior is not a bug but something working as intended.

Best Regards,

Jonathan

**Comment by codyspeck** [comment]
Ah, that works perfectly. Thank you for clearing that up for me!
