### ISSUE TITLE
Problems with Postgres Database and TimeSpan

### ISSUE THREAD

**Issue by rajkamal0610** [zzzprojects/Bulk-Operations#62]
I am trying bulk insertion from datatable which contains timespan columns. On insertion to database, while using bulk operation, the following error occurs

![20210302_123601.jpg](https://user-images.githubusercontent.com/8022900/109611296-08339680-7b54-11eb-8904-53275c96176b.jpg)

**Comment by JonathanMagnan** [comment]
Hello @rajkamal0610 ,

Can you explain to us more why your `TimeSpan` is currently a string? (This is what we understand by looking at the error message).

At this moment, we are not sure if we have enough information to try to reproduce the exact same error as you to fix it.

Let us know more about your entity, type, and database mapping.

If you can, a runnable project will be even better (you can send it in private here: info@zzzprojects.com)

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @rajkamal0610 

Since our last conversation, we haven't heard from you. 

As mentioned in my previous message, we are not sure if we have enough information to try to reproduce the exact same error as you to fix it.

Let us know more about your entity, type, and database mapping.

Don't hesitate to provide a private project to our support email:  info@zzzprojects.com

Jon

**Comment by JonathanMagnan** [comment]
Hello @rajkamal0610 ,

A simple reminder that we are here to assist you!

feel free to provide a private project to our support team: info@zzzprojects.com 

Looking forward to hearing from you, 

Jon

**Comment by rajkamal0610** [comment]
Its working. Thanks
