### ISSUE TITLE
Issue with insert into SQL Server table from ExpandoObject

### ISSUE THREAD

**Issue by chillifoot** [zzzprojects/Bulk-Operations#7]
Hello,

I have an expando object which has key values that have full stops in the name i.e. Avg. Position. The table in SQL Server has the exact same column names, however, the BulkInsert does not work as it seems to complain about the columns with a full stop in. The error message is:-

' Position' is not a member of type 'System.Object'

Interestingly if I remove the full stops from the table column name (Avg Position) the data inserts even if the key in the expando object still has them in (Avg. Position) 

The table is created on the fly depending on the return json from any number of API calls so I would like to avoid having to amend the column names in code if possible.

Are you able to look into this issue?

Many thanks

C

**Comment by JonathanMagnan** [comment]
Hello @chillifoot ,

Thank you for reporting this issue.

We will investigate the problem tomorrow.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @chillifoot ,

After investigating the issue, it seems to be caused because our library try to be "smart"

When a dot character is found, we expect it to be navigation property `Item.Avg.Position`, in your case, since you use an Expando Object, it can be a dictionary entry name instead.

The v2.10.59 has been released
https://www.nuget.org/packages/Z.BulkOperations/

In this version, we will automatically use a dictionary entry name if a "dot" character and "space" is found in an Expando Type.

We also added a new global option `BulkOperationManager.ForceExpandoAsDictionaryEntryName` to force all mapping in an expando object to be treated as a dictionary entry name.

> We could not automatically treat this case automatically to stay backward compatible

Let me know if the new version is now working for you

Best Regards,

Jonathan

**Comment by chillifoot** [comment]
Hello Jonathan,

Apologies for the delay and thanks for implemting so quickly. It all works a treat, however, when I try to get the rows exported using the RowsAffected property I get a -1 figure. What am I missing?

            var bulk = new BulkOperation(_connection);
            bulk.DestinationTableName = "[" + _schemaName + "].[" + _tableName + "]";
            bulk.UseLogDump = true;
            bulk.BulkInsert(expando);
            var result = bulk.RowsAffected;

Thanks

C

**Comment by chillifoot** [comment]
Also, how do I use the global option (BulkOperationManager.ForceExpandoAsDictionaryEntryName) in code?

**Comment by JonathanMagnan** [comment]
Hello @chillifoot ,

**RowAffected**
You are missing nothing. The RowAffected only work currently with UpdateFromQuery && DeleteFromQuery feature.

We are currently coding the next major version, so we are not sure yet if we will do some quick fix to update this current version with small improvement like this one or focus on the next major release.

**BulkOperationManager.ForceExpandoAsDictionaryEntryName**
You should apply this configuration globally at the same place you will add the license if you active it from the code:

- Web App: Use Application_Start in global.asax
- WinForm App: Use the main thread method
- Win Service: Use the OnStart method

Let me know if I answered correctly to all your questions.

Best Regards,

Jonathan

**Comment by chillifoot** [comment]
Thanks Jonathan for the quick reply.

**RowsAffected** Okay, thanks for the confirmation. I will keep an eye out for the next version.
**BulkOperationManager** A little confused here. The only object we are instantiating is the BulkOperation object so currently not using the BulkOperationManager nor are we adding a license in code. Please could you elaborate?

Thanks

C

**Comment by JonathanMagnan** [comment]
Hello C,

Sorry, it took me a few minutes to remember this request correctly.

In your case, we found a space after the dot `Avg. Position`, so our code what smart enough to understand is should be treated as a dictionary entry name automatically.

However, if you remove the space `Avg.Position`, this time, our code will fail since it will first try to use it as a property. This time, you will need to enable `BulkOperationManager.ForceExpandoAsDictionaryEntryName = true` to make it work.

So I believe you have nothing to do yet as long as there is a space after the dot.

Best Regards,

Jonathan

**Comment by chillifoot** [comment]
Great. Thank you!.

**Comment by JonathanMagnan** [comment]
Closing comment: Issue fixed
