### ISSUE TITLE
V5.1.8 Trail expried 2024-11-05

### ISSUE THREAD

**Issue by loganathas88** [zzzprojects/Bulk-Operations#79]
the Z.bulkopertions V.5.1.8 i just upated in 2024-11-01, but today error message is popup that trail period has been expired date 2024-11-05. kindly assist us to resolve the problem.
![Uploading Untitled.gif…]()

**Comment by JonathanMagnan** [comment]
Hello @loganathas88 

Sorry for the inconvenience, we are currently working on releasing a new trial and it will be available shortly. 

The trial expires at the end of each month. We do not recommend that you use the trial in a production machine or client machine; Occasionally, there may be a lapse of a few days between releases. 

That said, we highly suggest that companies purchase a license so that they won’t have to update their production environment every month. 

Don't hesitate to contact us for further information regarding our product. 

Jon

**Comment by loganathas88** [comment]
Dear Jon,

thanks for update and i will try to purchase a license version.

**Comment by NaRaine** [comment]
Hi Jon,

we too are having an expiry issue with the last update. We are looking to purchase a 4 dev licence but we need to know if this requires registration back to your servers when we deploy the exe? Is it just a matter of a code line in the exe with the key?

Thanks
Anthony

**Comment by JonathanMagnan** [comment]
Hello @NaRaine ,

No internet access, register key, or anything else you would not want on your production server is required.

You simply add the license to your project: https://bulk-operations.net/licensing

Best Regards,

Jon

**Comment by JonathanMagnan** [comment]
Hello @loganathas88 , @NaRaine ,

A new version with the trial correctly enabled has just been released: https://www.nuget.org/packages/Z.BulkOperations/5.1.9

Best Regards,

Jon
